### ISSUE TITLE
Choose curation table design

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/curation#1]
## This ticket is intended for discussion/review of curation table design options. 

The following description assumes image addition, but the system should be east to extend for other data types.

### Curation tables need to be able to:

1. **Add metadata for NEW images to the VFB KB**:  
   * This process generates new VFB IDs for images (more strictly image channel) and the anatomical entities they depict (currently we only support one anatomical entity per image), linking these to each other and to the template to which they are registered and incorporating the original image filename.  All new entities *must* be linked to a DataSet
2. **Add typing information for NEW images**: e.g confocal; TEM
3. **Add non-semantic metadata to images**: e.g. centre point; index number (for painted domains) 
2. **Add classification(s) for an anatomical structure depicted in a NEW or existing image (e.g. Kenyon cell):** 
2. **Add relationships for an anatomical structure depicted in a NEW or existing image : e.g. part_of adult brain:** 

### Design decisions:

1. IDs vs names or both?
   * IDs alone => hard to spot errors
   * IDs + names => Consistency between two can be checked.  But we need a way to link pairs of columns (or only refer to one entity per row).
   * names => Greater dependency on: ontology/FlyBase versions; Name uniqueness
2. How much information should we cram into a single row?
   * What is the minimum information required for adding an image? 
   * Should we allow arbitrarily large amounts of classification/relationships to be added while adding an image? 
2. Do we allow multiple entities to be referenced in one cell? 
    * If so what is delimiter? (suggest '|')).
    *  If this is combined with curation of IDs + names it => danger of fencepost errors. 
2. Do we have separate curation record types for adding new images and for extending annotation on existing, or do we have just one, flexible record type.

**Comment by dosumis** [comment]
## Current design

[New image curation table](https://github.com/VirtualFlyBrain/curation/tree/master/records/new_images) - draft.

### Design decisions:

> 1. IDs vs names or both?

IDs alone 

> 2. How much information should we cram into a single row?
>  * What is the minimum information required for adding an image?

1. Imaging modality; template; dataset: specified for whole curation record using a yaml file.
1. filename; label; anatomical type; part_of:  in TSV

Note - it is easier if image specific data is added at the same time as images are added. e.g. centre-point; index number

> * Should we allow arbitrarily large amounts of classification/relationships to be added while adding an image.  

We do this by having names column headers for relationships.

We define minimal information in one row using 

> 3. Do we allow multiple entities to be referenced in one cell?

Yes. Delimited with '|'

> 4. Do we have separate curation record types for adding new images and for extending annotation on existing, or do we have just one, flexible record type.

We have separate record types: [New image curation table](https://github.com/VirtualFlyBrain/curation/tree/master/records/new_images); [Annotation](https://github.com/VirtualFlyBrain/curation/tree/master/records/annotations)

Unlike new_images, annotation tables have a limited number of columns, with the minimum being: subject (individual_ID), relation, object

**Comment by dosumis** [comment]
### Proposal:

1.  All curation uses names, not IDs
2.  Dataset addition table (YAML?):  short_name; label; description; license; pub*
2.  Naming convention for image curation files:  Type_DataSet_creation_date.tsv; Type_DataSet.yaml:
2.  When adding new content, details that apply to all rows are specified in a YAML file: Template; imaging_modality....
3.  Curation table Types:
  * Types for adding new images all have columns:  filename; label; synonyms; {dbxrefs}; {index}; {centre}; Specific types for adding new images:
     * Expression pattern (EP): Driver*; part_of
      *  Split (Split): DBD*; AD*; PART_OF
      * Anatomy (Anat): IS_A; PART_OF; {EXPRESSES*}  
  * Type for extending annotation on existing term:
      *  Free (free): Subject^; Relation; Object # Subject = name of anatomical individual.

\*  Addition script checks public FlyBase for validity & adds to KB.  In the case of pubs, DOIs are also allowed for pre-prints - FlyBase check only happens if ID = FBrf. 
^ Referring to anatomical individuals by name might be too risky.  It will be increasingly a hard to keep name uniqueness.  Might be better to have name/ID pair in these cases and cross-check.

**Comment by dosumis** [comment]
Notes on implementation

Loading scripts/methods:

  All addition of new images goes via     - KBtools.KB_pattern_writer.add_anatomy_image_set
This is typically used in short_form addition mode, but it does have an option for matching on labels.  Need to decide if this is safe, or if a more restricted lookup should be added first.

   Adding EP or split requires 2 steps:  Addition of EP or Split class followed by regular anatomy image set addition: Methods:

features_tools.FeatureMover.generate_expression_patterns
features_tools.FeatureMover.gen_ep_split_feat

Both of these methods take short_form IDs for features, so need wrapping.  But this will be necessary for adding a FlyBase lookup step anyway.

File syntax checking:  YAML driven scripts already in place - some wrapping needed for file name conventions.

**Comment by aoifelarkin** [comment]
Any chance of an example of some real data in relation to this? Having a bit of trouble relating some of your descriptions to the kind of information received from authors.

**Comment by dosumis** [comment]
> Any chance of an example of some real data in relation to this?

Yep.  I'm planning to make example TSVs for:

New images  for:
    - neurons from EM data 
    - single neurons from confocal data (with drivers)
    - splits
Extending annotations on loaded images

**Comment by gm119** [comment]
Hi @dosumis, I'd like to add myself as an assignee to this one to make sure I keep in the loop, but neither Aoife, Clare or I have the relevant permissions (we can't see the little settings wheel that is normally to the right of 'Assignees' 'labels' etc ! this seems to just be an issue for the curation repository (we can see this on management) Can you tweak the settings for us, ta

**Comment by dosumis** [comment]
Should work now.

**Comment by dosumis** [comment]
Example of curation table for - single neurons from confocal data (with drivers): [TSV](https://github.com/VirtualFlyBrain/curation/blob/test_curation/records/new_images/anat_Shih2015_191010.tsv), [YAML](https://github.com/VirtualFlyBrain/curation/blob/test_curation/records/new_images/anat_Shih2015.yaml)

**Comment by dosumis** [comment]
[documentation of fields in example anatomical image curation table](https://github.com/VirtualFlyBrain/curation/blob/test_curation/records/new_images/anatomy_spec.yaml)

**Comment by dosumis** [comment]
### TODO
1. Add column for name_in_source
2. In spec - add flag for fields that are typically manually curated.
3. Add dataset to yaml
