### ISSUE TITLE
loading anat records with existing short_forms (for FlyWire)

### ISSUE THREAD

**Issue by Clare72** [VirtualFlyBrain/curation#114]
Setting --allow_duplicates now prevents failure (though warnings are still printed) when trying to load anat records for existing VFB short_forms (for FlyWire neurons).

Currently, the existing entities to load seem to be handled the same as new entities (i.e. same cypher is generated), but this does not seem to be overwriting/updating any existing nodes, only generating new if there was nothing before:
```
match (i:Individual)-[r:has_source]->({short_form:'Dorkenwald2023'}) 
optional match (i:Individual)-[a {short_form:'hasDbXref'}]->({short_form:'flywire630'}) 
optional match (i:Individual)-[b {short_form:'hasDbXref'}]->({short_form:'flywire783'}) 
return count(distinct r) as all_FlyWire, count(distinct a) as old, count(distinct b) as new
```
all_FlyWire|old|new
-|-|-
139291|135726|3565

I think we may need to change the statements to work for existing or new entities. I am not sure exactly what to do, but looking at [documentation](https://neo4j.com/docs/cypher-manual/current/clauses/merge/), maybe we need to just MERGE the node itself (rather than full pattern), then use ON MATCH or ON CREATE to update or add the other information?

**Comment by dosumis** [comment]
Seems odd. IIRC there's distinct record type for modifiying existing records. Are you saying that this has never worked?

**Comment by Clare72** [comment]
This is new functionality to replace the old (v630) flywire neurons with v783
After Robbie's edits to allow duplicate short_forms, I think it was supposed to work using an anat record @Robbie1977 please clarify if this is not what was intended(?)

**Comment by Robbie1977** [comment]
I don't think we ever envisaged changing the xrefs as part of the curation load as this would presuppose you know which to remove/is being replaced so this will always need to be something done (very carefully) manually in cypher.

**Comment by Clare72** [comment]
so what was supposed to be updated with the new load?

**Comment by Robbie1977** [comment]
@Claire the current behaviour isn't terrible in that creates the new individuals and correct xrefs and just the old links are required to move to the new this issue we have is checking if any of the previous neurons no longer exist and depreciate and link to replacement (if any)

**Comment by Robbie1977** [comment]
> so what was supposed to be updated with the new load?

The label and description are updated to the new ones as @admclachlan tested this when we implemented the predefined short_form loading

**Comment by Robbie1977** [comment]
New annotation should be added as per usual via the new Meta loading

**Comment by Clare72** [comment]
looks like the old labels haven't been updated:
`match (i:Individual)-[r:has_source]->({short_form:'Dorkenwald2023'}) where i.label starts with 'FlyWire_783' return count(i)`
3565

**Comment by Robbie1977** [comment]
Let me look at the code as we have the issue with xrefs and short_forms being both seem as the primary id for curation loading it's causing issues over just loading basic info
