### ISSUE TITLE
Specify curation table design YAML + build test tables

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/curation#2]
Table for adding new anatomical images: [spec](https://github.com/VirtualFlyBrain/curation/blob/test_curation/records/new_images/anatomy_spec.yaml), Examples: [single neurons from confocal data (with drivers)](https://github.com/VirtualFlyBrain/curation/blob/test_curation/records/new_images/anat_Shih2015_191010.tsv)

**Comment by gm119** [comment]
Hi @dosumis, I'm trying to get to the nice doc you presented last week for the different kinds of image curation, but the links in this ticket don't work.

I've eventually found the relevant link here (adding in case I get lost again !): https://github.com/VirtualFlyBrain/curation/wiki/Curation-wiki--Home

**Comment by dosumis** [comment]
Doc here: https://github.com/VirtualFlyBrain/curation/wiki/Curation-wiki--Home
