### ISSUE TITLE
Set up Jenkins server for loading curation to kbw

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/curation#23]
See .travis.yaml on [dosumis_curation](https://github.com/VirtualFlyBrain/curation/tree/dosumis_curation) branch for how to run. Loadable files are already in this branch and will accumulate as the number of new curation types increases.  I aim to keep the branch sufficiently up-to-date with master to load whatever is there.

**Comment by Robbie1977** [comment]
To be run weekly/biweekly - to be checked
