### ISSUE TITLE
10K+ hasDbXref relations are missing iri property 

### ISSUE THREAD

**Issue by matentzn** [VirtualFlyBrain/curation#41]
```
MATCH p=()-[r:hasDbXref]->() WHERE NOT EXISTS(r.iri) RETURN count(p)
```

Simply set to the iri property to `http://www.geneontology.org/formats/oboInOwl#hasDbXref`.

**Comment by dosumis** [comment]
Ooops.  Probably from manual addition.  This should never happen if edges are added through KB_tools.

**Comment by dosumis** [comment]
Need some general scripts to check for this kind of schema violation after manual edits.

**Comment by dosumis** [comment]
Fixed

```cql
MATCH p=()-[r:hasDbXref]->() WHERE NOT EXISTS(r.iri) 
SET r.type =  "Annotation" 
SET r.iri =  "http://www.geneontology.org/formats/oboInOwl#hasDbXref" 
SET r.short_form =  "hasDbXref"
```
