### ISSUE TITLE
Request KB fixed IRIs for production, staging and block

### ISSUE THREAD

**Issue by matentzn** [VirtualFlyBrain/curation#54]
To ensure the embargo code is 100% stable, can we get AnnotationProperty nodes for 

- [ ] production
- [ ] staging
- [ ] block

Otherwise, I will work with these autogenerated IRIs, which may be unstable if one day you decide to introduce APs!

**Comment by matentzn** [comment]
@dosumis when done assign to @matentzn not close

**Comment by dosumis** [comment]
Trying to think through the most generic way to do this.  If we these are to potentially form part of a generic pipeline, then I don't want to give them VFB iris. 

@matentzn  = How do autogenerated IRIs look?  Can we give them a stable generic pattern? (not tied to VFB?)

**Comment by matentzn** [comment]
Check this example:

http://ts.p2.virtualflybrain.org/rdf4j-workbench/repositories/vfb/explore?resource=%3Chttp%3A%2F%2Fn2o.neo%2Fcustom%2Fproduction%3E&limit_explore=100&show-datatypes=show-dataypes

**Comment by matentzn** [comment]
The pipeline generates iris like:

```
http://n2o.neo/custom/x
```

whenever a property x is not mapped to an OWL property. The built-in properties like nodeLabel etc use a slightly different IRI:

http://n2o.neo/property/nodeLabel

Example:
http://ts.p2.virtualflybrain.org/rdf4j-workbench/repositories/vfb/explore?resource=%3Chttp%3A%2F%2Fn2o.neo%2Fproperty%2FnodeLabel%3E&limit_explore=100&show-datatypes=show-dataypes

**Comment by dosumis** [comment]
Happy for these to be internal.

**Comment by Robbie1977** [comment]
From my point of view, I need a block:
```
(i:Individual {block:true})<-[:depicts]-(ch:Individual {block:true})<-[:in_register_with {block:true}]-(t:Template)
```
1) for removing the whole anatomical individual and all images (nodes and edges) up to the template,
2) on the channel to remove itself and any edges from it.
3) the in_register_with edge to remove that single edge hence a single alignment.

**Comment by dosumis** [comment]
Spec now here :https://github.com/VirtualFlyBrain/neo4j2owl/issues/52
