### ISSUE TITLE
Should we be curating pub for each classification assertion?

### ISSUE THREAD

**Issue by admclachlan** [VirtualFlyBrain/curation#77]
Update curation repo policy doc to link to papers.

Scenario:  If one neuron is in 2 datasets in CATMAID, is it possible for it to be given different names/mappings in each?  If so, we can record each association in the KB as edge annotations.

@robbie1977 is this possible in CATMAID (L1?)

**Comment by admclachlan** [comment]
Fields:
new_image.classification_reference
new_metadata.pub

**Comment by dosumis** [comment]
Conclusion - use this wherever possible - but it's often confusing given the nature of pipelines through CATMAID.
