### ISSUE TITLE
Block all newly loaded images on loading

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/curation#80]
Can we add a 'block="New Data"' on all new Anatomical Individual nodes created so all new data is embargoed until images are loaded.

**Comment by dosumis** [comment]
Edit kb_pattern_writer.add_anatomy_image_set https://github.com/VirtualFlyBrain/VFB_neo4j/blob/master/src/uk/ac/ebi/vfb/neo4j/KB_tools.py#L865

Make sure "block":"New Data" ends up in the anatomy_attributes dictionary.  You could make this configurable via a kwarg with default value.

 Might be better to have a boolean.  Image_added: False.
