### ISSUE TITLE
Can we add fasciculates_with column in new images

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/curation#89]
we have nerve annotations that could also be loaded into curation tsv

**Comment by dosumis** [comment]
Should be possible by editing configs alone.   You can test by adding extra files to https://github.com/VirtualFlyBrain/curation/tree/master/src/vfb/curation/test/resources/records/new_images

@admclachlan - do you want to have a go and add me as PR reviewer?

**Comment by dosumis** [comment]
Alternatively - just add this to the supported relations here: https://github.com/VirtualFlyBrain/curation/blob/master/records/relations_spec.yaml

And add this in 2 steps: new images, then new_metadata.  See  this comment: https://github.com/VirtualFlyBrain/curation/issues/88#issuecomment-957302570
